---
title: "Health Outcomes in 500 Major U.S. Cities"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(stringr)
```

```{r, echo = FALSE}
cdc_df = read_csv("./data/cdc_df.csv") %>%
  mutate(city_state = str_c(PlaceName, StateAbbr, sep = ", "))

outcome_transform = cdc_df %>% 
  gather(key = outcome, value = prevalence, BPHIGH_AdjPrev, CANCER_AdjPrev, CHD_AdjPrev, COPD_AdjPrev,    DIABETES_AdjPrev, HIGHCHOL_AdjPrev, OBESITY_AdjPrev, PHLTH_AdjPrev, STROKE_AdjPrev) %>% 
  mutate(outcome = str_replace(outcome, "_AdjPrev", ""), 
        outcome = recode(outcome, 'BPHIGH' = 'High Blood Pressure',
                                  'CANCER' = 'Cancer',
                                  'CHD' = 'Coronary Heart Disease',
                                  'COPD' = 'Chronic Obstructive Pulmonary Disease',
                                  'DIABETES' = 'Diabetes',
                                  'HIGHCHOL' = 'High Cholesterol',
                                  'OBESITY' = 'Obesity',
                                  'PHLTH' = 'Poor Physical Health',
                                  'STROKE' = 'Stroke')) %>%
  select(city_state, ACCESS2_AdjPrev, Population2010, Geolocation, health_exp, region, division, outcome, prevalence) 
```


Column {.sidebar}
-----------------------------------------------------------------------
These plots illustrate the relationship between prevalence of health outcomes and health factors (i.e. lack of insurance and health expenditure) in 500 major U.S. cities. Cities are regionalized into Midwest, Northeast, South, and West regions. The data come from the Centers for Disease Control and Prevention, and can be found [here](https://chronicdata.cdc.gov/500-Cities/500-Cities-City-level-Data-GIS-Friendly-Format-201/k56w-7tny/). The Git repository for this Shiny document can be found [here](https://github.com/dayoungyu/final_plots).

```{r}

outcomes = outcome_transform %>% distinct(outcome) %>% pull()
regions = cdc_df %>% distinct(region) %>% pull()

selectInput("outcome_choice", label = h3("Select Health Outcome"),
    choices = outcomes, 
    selected = "Cancer")

```



Column {data-width=600}
-----------------------------------------------------------------------
### Lack of Health Insurance on Health Outcome Prevalence

```{r}
renderPlotly({outcome_transform %>%
  mutate(text_label = city_state) %>%
  filter(outcome == input$outcome_choice) %>%
  plot_ly(x = ~ACCESS2_AdjPrev, y = ~prevalence, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~region,
          text = ~text_label
          ) %>%
  layout(
    xaxis = list(title = "Prevalence of Uninsured in City"),
    yaxis = list(title = "Prevalence of Health Outcome")
  )
})
```


Column {data-width=400}
-----------------------------------------------------------------------

### Health Expenditure by City and Health Outcome Prevalence

```{r}
renderPlotly({outcome_transform %>%
  mutate(text_label = city_state) %>%
  filter(outcome == input$outcome_choice) %>%
  plot_ly(x = ~health_exp, y = ~prevalence, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~region,
          text = ~text_label
          ) %>%
  layout(
    xaxis = list(title = "Health Expenditure"),
    yaxis = list(title = "Prevalence of Health Outcome (millions)")
  )
})
```

